### PR TITLE
Added "Latest Release/Snapshot"

### PR DESCRIPTION
**Pull request by StrangeOne101**
- Added "Latest Release" and "Latest Snapshot" options. This fetches the latest from mojangs servers and patches it
- Made the version GUI box no longer have underscores. Underscores are still used for the command line version, though
- This uses org.json to parse the version manifest files. It's lightweight and is shaded in like the rest of the libraries
- Moved the version to 2.2

### CODE REVIEW

**Comment by StrangeOne101** [comment]
Issue has been fixed on the main repo, but I didn't realize McDeob uses a fork that helps with the implementation. May take quite a lot of work to port.

**Comment by ShaneBeee** [comment]
I had to fork it, to change a few things to work with this program.
When I have some spare time, Ill try update my fork.

It shouldn't be too big of an issue, unless they did major changes (they did it once before and I had a hell of a time updating)

**Comment by ShaneBeee** [comment]
I did updates of both Reconstruct and FernFlower. 
Everything in the app seems to run fine now.

I have to change a few things around, due to how Reconstruct changed their layout, but you should be able to update your PR accordingly.

**Review by ShaneBeee — APPROVED** [review]
I did some small fixes, and this looks good to go. 
Just doing some last minute testing first.

**Pull request merged**
